/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.findlaw.titanium.c2dm;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;

import com.google.android.c2dm.C2DMessaging;

@Kroll.module(name="C2dm", id="com.findlaw.titanium.c2dm")
public class C2dmModule extends KrollModule
{
	// Standard Debugging variables
	private static final String LCAT = "C2dmModule";
	
	private static C2dmModule _THIS;
	
	public C2dmModule(TiContext tiContext) {
		super(tiContext);
		
		_THIS = this;
	}

	// Methods
	@Kroll.method
	public void register(String senderId) {
		Log.d(LCAT, "register called");
		
        C2DMessaging.register(getTiContext().getTiApp(), senderId);
	}
	
	// Properties
	@Kroll.getProperty
	public String getRegistrationId() {
		Log.d(LCAT, "get registrationId property");
		return C2DMessaging.getRegistrationId(getTiContext().getTiApp());
	}
	
	
	static C2dmModule getInstance() {
		return _THIS;
	}

}
